todoproject/todoapp/urls.py
from django.urls import path
from . import views
app_name='todoapp'
urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id1>/', views.update, name='update'),
    path('cbvhome/',views.tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.taskdetailview.as_view(),name='cbvdetail'),
    path('cupdate/<int:pk>/',views.taskupdateview.as_view(),name='cupdate'),
    path('cdelete/<int:pk>/',views.taskdeleteview.as_view(),name='cdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path,include

from todoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from django import forms
from .models import task

class taskform(forms.ModelForm):
    class Meta:
        model=task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .models import task
from .forms import taskform
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


# Create your views here.

class tasklistview(ListView):
    model=task
    template_name='home.html'
    context_object_name = 'task1'

class taskdetailview(DetailView):
    model=task
    template_name='detail.html'
    context_object_name = 'task'

class taskupdateview(UpdateView):
    model=task
    template_name='update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')


    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail', kwargs={'pk': self.object.id})



class taskdeleteview(DeleteView):
    model = task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

def add(request):
    task1=task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date = request.POST.get('date', '')
        Task=task(name=name,priority=priority,date=date)
        Task.save()
    return render(request,"home.html",{'task1':task1})
def delete(request,id):
    if request.method =='POST':
        tasks = task.objects.get(id=id)
        tasks.delete()
        return redirect('/')
    return render(request, "delete.html")
def update(request,id1):
    task2=task.objects.get(id=id1)
    form=taskform(request.POST or None,instance=task2)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'task':task2})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:LightCyan";>
{% block body%}
{% endblock %}

</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}|
    ARE YOUR SURE THIS TASK DONE?
    <input style="background-color: red; color: white;" type="submit" value="CONFIRM">
</form>
{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="shadow card">
                <div class="card-body">
                    <h3 class="card-title">{{task.name}}</h3>
                    <P><b>{{task.priority}}</b></P>
                    <P><b>{{task.date}}</b></P>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}"><b>DONE</b></a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}"><b>UPDATE</b></a>
                </div>
            </div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input style="background-color: green; color: white;" type="submit" value="UPDATE" >
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1><b>ToDo</b></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
    <div class="col-md-6 mt-3">
        <form method="POST" class="p-3 shadow bg-white surrounded">
    {% csrf_token %}
    <div class="form-group">
       <input type="text" class="form-control" name="task" placeholder="TaskName">
    </div><br>
    <div class="form-group">
       <input type="text" class="form-control" name="priority" placeholder="Priority">
    </div><br>
    <div class="form-group">
       <input type="date" class="form-control" name="date" placeholder="Enter your Date">
    </div><br>
    <input type="submit" class="btn btn-success">
</form>

    </div>
        <div class="col-md-6 mt-3">
            <h4><B>Task To Be Completed</b></h4>
            {% for i in task1 %}
            <div class="shadow card">
                <div class="card-body">
                    <h3 class="card-title">{{i.name}}</h3>
                    <P><b>{{i.priority}}</b></P>
                    <P><b>{{i.date}}</b></P>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}"><b>DONE</b></a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}"><b>UPDATE</b></a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
</div>
    </div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
        <div class="shadow card">
                <div class="card-header">
                    <div class="card-title">
                        <h3><b>Task Update</b></h3>
                    </div>
                        <div class="card-body">
                         <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input style="background-color: green; color: white;" type="submit" value="UPDATE" >
                </form>
                        </div>
                </div>
        </div>
{% endblock %}